# Generated by Django 6.0.1 on 2026-02-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_add_internal_ops_intel'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreport',
            name='web_sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
