# Generated by Django 6.0.1 on 2026-03-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_add_research_enrichment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorcasestudy',
            name='source_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
